### ISSUE TITLE
allow posting images to private DMs, groups and channels

### ISSUE THREAD

**Issue by aredridel** [lgbtq-technology/lgbtq-helper-app#3]

**Comment by heypano** [comment]
Added support for groups here: https://github.com/PublicRelay/com.publicrelay.www/pull/2709/files

**Comment by heypano** [comment]
Should be fully implemented by this https://github.com/lgbtq-technology/lgbtq-helper-app/pull/23/files

**Comment by aredridel** [comment]
Fixed by #23!
